services:
  valkey:
    image: valkey/valkey
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" 
    volumes:
      - ./qdrant-data:/qdrant/storage


volumes:
  qdrant-data: